[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"
buildCommand = "pip install -e ."

[environments.development]
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port $PORT --reload"
buildCommand = "pip install -e .[dev]"

# Configurações específicas do Railway
[nixpacks]
pythonVersion = "3.11"

[nixpacks.phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[nixpacks.phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -e ."
]

[nixpacks.phases.build]
cmds = [
    "python -m compileall src/",
]

# Variáveis de ambiente necessárias
[variables]
PYTHONPATH = "/app/src"
PYTHONUNBUFFERED = "1"
PORT = "8000"
